/*
 MIT License (c) copyright B Cavalier & J Hann */
window.curl&&alert("DUEL included more than once!");
(function(){var b=function(a){return typeof a!=="undefined"};if(!b(window.$sf))window.$sf={};var a=window.$sf;if(!b(a.env))a.env="prod";a.env_cdn="wsimg.com";a.proto="https:"==document.location.protocol?"https:":"http:";if(!b(a.plabel))a.plabel=1;if(!b(a.skin))a.skin="app";if(!b(a.theme))switch(a.skin){case "app":a.theme=a.plabel==1?"app":"app.pl";break;case "fos":switch(a.plabel){case 1:a.theme="fos";break;case 2:a.theme="fos.pl2";break;case 1387:a.theme="fos.pl1387";break;default:a.theme="fos.pl";
break}default:a.theme=a.skin}if(!b(a.culture))a.culture="en";if(!b(a.preload))a.preload=1;if(!b(a.loader))a.loader=2;if(!b(a.base))a.base={};if(!b(a.util))a.util={};if(!b(a.getjQuery))a.getjQuery=function(){return window.jQuery};if(!b(a.require))a.require={};if(typeof a.require.local==="string")a.preload=0,a.loader=1;if(!b(a.require.js_root))a.require.js_root=a.proto+"//web.archive.org/web/20141119215833/http://img4./"+a.env_cdn+"/starfield/duel/v2.3.2";if(!b(a.require.img5_root))a.require.img5_root=a.proto+"//web.archive.org/web/20141119215833/http://img5./"+a.env_cdn+"/starfield/duel/v2.3.2";
if(!b(a.require.jquery))a.require.jquery=a.proto+"//web.archive.org/web/20141119215833/http://img4.wsimg.com/starfield/jquery/v1.7.2/jquery.js";if(!b(a.require.css_root))a.require.css_root=a.proto+"//web.archive.org/web/20141119215833/http://img2./"+a.env_cdn+"/starfield/duel/v2.3.2";if(!b(a.require.img_root))a.require.img_root=a.proto+"//web.archive.org/web/20141119215833/http://img1./"+a.env_cdn+"/starfield/duel/v2.3.2";if(!b(a.require.core))a.require.core=a.require.js_root+"/starfield/duel/v2.3.2/sf.core/sf.core";if(!b(a.require.core_css))a.require.core_css=a.require.css_root+"/starfield/duel/v2.3.2/sf.core/sf.core."+a.theme+
".css";if(!b(a.bundle))a.bundle={};b=a.bundle;b["sf.growl"]=b["sf.tabs"]=b["sf.dialog"]=b["sf.alerts"]=b["sf.msg.overlay"]=b["sf.base.dialog"]=b["sf.base.modal"]=b["sf.base.flyout"]=b["sf.i18n/duel"]="sf.core.pkg";b={pluginPath:a.require.js_root+"/curl/plugin",paths:{},apiName:"require"};if(typeof a.baseUrl=="string")b.baseUrl=a.baseUrl;if(typeof a.debug!="undefined")b.debug=a.debug;if(typeof a.require.paths==="object")for(p in a.require.paths)b.paths[p]=a.require.paths[p];window.curl=b})();
(function(b){function a(){}function c(a,c){return z.call(a).indexOf("[object "+c)==0}function d(a){return a&&a.charAt(a.length-1)=="/"?a.substr(0,a.length-1):a}function h(a,c){var b,d,e;d=1;a=a.replace(J,function(a,c,F){F&&d++;e=!0;return""});return e?(b=c.split("/"),b.splice(b.length-d,d),b.concat(a||[]).join("/")):a}function g(a){var c=a.indexOf("!");return{resourceId:a.substr(c+1),pluginId:c>=0&&a.substr(0,c)}}function f(){}function e(a){f.prototype=a;a=new f;f.prototype=x;return a}function i(){function c(a,
b,d){e.push([a,b,d])}function b(a,c){for(var d,F=0;d=e[F++];)(d=d[a])&&d(c)}var d,e,g;d=this;e=[];g=function(d,f){c=d?function(a){a&&a(f)}:function(a,c){c&&c(f)};g=a;b(d?0:1,f);b=a;e=q};this.then=function(a,b,e){c(a,b,e);return d};this.resolve=function(a){d.resolved=a;g(!0,a)};this.reject=function(a){d.rejected=a;g(!1,a)};this.progress=function(a){b(2,a)}}function j(a,c,b,d){return a instanceof i?a.then(c,b,d):c(a)}function k(a,c,b){return function(){var d;--a>=0&&c&&(d=c.apply(q,arguments));a==0&&
b&&b(d);return d}}function l(){function a(c,b,d){var e;e=m.createContext(n,q,[].concat(c));this.then=c=function(a,c){j(e,function(c){a&&a.apply(q,c)},function(a){if(c)c(a);else throw a;});return this};this.next=function(c,b){return new a(c,b,e)};b&&c(b);j(d,function(){m.getDeps(e)})}var b=[].slice.call(arguments);c(b[0],"Object")&&(n=m.extractCfg(b.shift()),m.checkPreloads(n));return new a(b[0],b[1])}function o(a){var c=a.id;if(c==q)if(C!==q)C={ex:"Multiple anonymous defines in url"};else if(!(c=
m.getCurrentDefName()))C=a;if(c!=q){var b=s[c];if(!(c in s))b=m.resolvePathInfo(c,n).config,b=s[c]=m.createResourceDef(b,c);if(b instanceof i)b.useNet=!1,m.defineResource(b,a)}}var n=b.curl,r=b.document,u=r&&(r.head||r.getElementsByTagName("head")[0]),w=u&&u.getElementsByTagName("base")[0]||null,y={},E={},A={},v="addEventListener"in b?{}:{loaded:1,complete:1},x={},z=x.toString,q,s={},t=!1,C,B=/\?/,H=/^\/|^[^:]+:\/\//,J=/(?:^|\/)(\.)(\.?)\/?/g,K=/\/\*[\s\S]*?\*\/|(?:[^\\])\/\/.*?[\n\r]/g,L=/require\s*\(\s*["']([^"']+)["']\s*\)|(?:[^\\]?)(["'])/g,
G,m;m={createContext:function(a,b,d,e){function g(a){return h(a,k.ctxId)}function f(b,d){var e,h,o,n;e=d&&function(a){d.apply(q,a)};if(c(b,"String")){h=g(b);o=s[h];n=o instanceof i&&o.exports;if(!(h in s))throw Error("Module not resolved: "+h);if(e)throw Error("require(id, callback) not allowed");return n||o}else j(m.getDeps(m.createContext(a,k.id,b)),e)}var k;k=new i;k.ctxId=k.id=b||"";k.isPreload=e;k.depNames=d;k.require=f;f.toUrl=function(c){return m.resolvePathInfo(g(c),a).url};k.toAbsId=g;return k},
createResourceDef:function(a,c,b,d){var e,g,f,i;e=m.createContext(a,c,q,b);e.ctxId=d==q?c:d;g=e.resolve;f=k(1,function(a){e.deps=a;try{i=m.executeDefFunc(e)}catch(c){e.reject(c)}});e.resolve=function(a){f(a);s[e.id]=i;g(i)};e.exportsReady=function(a){e.exports&&(f(a),e.progress(E))};return e},createPluginDef:function(a,c,b,d){a=m.createContext(a,c,q,b);a.ctxId=d;return a},getCjsRequire:function(a){return a.require},getCjsExports:function(a){return a.exports||(a.exports={})},getCjsModule:function(a){var c=
a.module;if(!c)c=a.module={id:a.id,uri:m.getDefUrl(a),exports:m.getCjsExports(a)},c.exports=c.exports;return c},getDefUrl:function(a){return a.url||(a.url=m.checkToAddJsExt(a.require.toUrl(a.id)))},extractCfg:function(a){function c(b,i){var k,j,o,n,l;for(l in b){o=b[l];n=a;j=g(d(o.id||o.name||l));k=j.resourceId;if(j=j.pluginId){n=f[j];if(!n)n=f[j]=e(a),n.pathMap=e(a.pathMap),n.pathList=[];delete b[l]}if(i){j=o;var t=void 0,D=void 0,t=j.path=d(j.path||j.location||""),D=j.main||"main";j.config=j.config;
j.main=D.charAt(0)=="."?d(h(D,t)):d(t)+"/"+D}else j={path:d(o)};j.specificity=k.split("/").length;k?(n.pathMap[k]=j,n.pathList.push(k)):n.baseUrl=m.resolveUrl(o,a)}}function b(a){var c=a.pathMap;a.pathRx=RegExp("^("+a.pathList.sort(function(a,b){return c[a].specificity<c[b].specificity}).join("|").replace(/\//g,"\\/")+")(?=\\/|$)");delete a.pathList}var f;a.baseUrl=a.baseUrl||"";a.pluginPath="pluginPath"in a?a.pluginPath:"curl/plugin";a.pathMap={};f=a.plugins=a.plugins||{};a.pathList=[];c(a.paths,
!1);c(a.packages,!0);for(var i in f){var k=f[i].pathList;if(k)f[i].pathList=k.concat(a.pathList),b(f[i])}b(a);return a},checkPreloads:function(a){var c;(c=a.preloads)&&c.length>0&&j(t,function(){t=m.getDeps(m.createContext(a,q,c,!0))})},resolvePathInfo:function(a,c,b){var e,g,f;e=c.pathMap;b&&c.pluginPath&&a.indexOf("/")<0&&!(a in e)&&(a=d(c.pluginPath)+"/"+a);b=H.test(a)?a:a.replace(c.pathRx,function(c){g=e[c]||{};f=g.config;return g.main&&c==a?g.main:g.path||""});return{path:b,config:f||n,url:m.resolveUrl(b,
c)}},resolveUrl:function(a,c){var b=c.baseUrl;return b&&!H.test(a)?d(b)+"/"+a:a},checkToAddJsExt:function(a){return a+(B.test(a)?"":".js")},loadScript:function(a,c,d){var e=r.createElement("script");e.onload=e.onreadystatechange=function(d){d=d||b.event;if(d.type=="load"||v[e.readyState])delete A[a.id],e.onload=e.onreadystatechange=e.onerror="",c()};e.onerror=function(){d(Error("Syntax or http error: "+a.url))};e.charset="utf-8";e.async=!0;e.src=a.url;A[a.id]=e;u.insertBefore(e,w)},extractCjsDeps:function(a){var c=
[],b;(typeof a=="string"?a:a.toSource?a.toSource():a.toString()).replace(K,"").replace(L,function(a,d,e){e?b=b==e?q:b:b||c.push(d);return""});return c},fixArgs:function(a){var b,d,e,g,f,i;f=a.length;e=a[f-1];g=c(e,"Function")?e.length:-1;f==2?c(a[0],"Array")?d=a[0]:b=a[0]:f==3&&(b=a[0],d=a[1]);!d&&g>0&&(i=!0,d=["require","exports","module"].slice(0,g).concat(m.extractCjsDeps(e)));return{id:b,deps:d||[],res:g>=0?e:function(){return e},cjs:i}},executeDefFunc:function(a){var c;c=a.res.apply(a.cjs?a.exports:
q,a.deps);if(c===q&&a.exports)c=a.module?a.exports=a.module.exports:a.exports;return c},defineResource:function(a,c){j(a.isPreload||t,function(){a.res=c.res;a.cjs=c.cjs;a.depNames=c.deps;m.getDeps(a)})},getDeps:function(a){function c(a,b,e){f[b]=a;e&&o(a,b)}function b(c,e){var d,g,f,h;d=k(1,function(a){g(a);l(a,e)});g=k(1,function(a){o(a,e)});f=m.fetchDep(c,a);(h=f instanceof i&&f.exports)&&g(h);j(f,d,a.reject,a.exports&&function(a){f.exports&&(a==y?g(f.exports):a==E&&d(f.exports))})}function d(){a.resolve(f)}
var e,g,f,h,n,o,l;f=[];g=a.depNames;h=g.length;g.length==0&&d();o=k(h,c,function(){a.exportsReady&&a.exportsReady(f)});l=k(h,c,d);for(e=0;e<h;e++)n=g[e],n in G?(l(G[n](a),e,!0),a.exports&&a.progress(y)):n?b(n,e):l(q,e,!0);return a},fetchResDef:function(a){m.getDefUrl(a);m.loadScript(a,function(){var c=C;C=q;a.useNet!==!1&&(!c||c.ex?a.reject(Error((c&&c.ex||"define() missing or duplicated: url").replace("url",a.url))):m.defineResource(a,c))},a.reject);return a},fetchDep:function(a,c){var b,e,d,f,k,
h,o,l,t,B;b=c.toAbsId;e=c.isPreload;d=g(a);h=d.resourceId;f=b(d.pluginId||h);o=m.resolvePathInfo(f,n,!!d.pluginId);if(d.pluginId)k=f;else if(k=o.config.moduleLoader)h=f,f=k,o=m.resolvePathInfo(k,n);l=s[f];if(!(f in s))l=s[f]=m.createResourceDef(o.config,f,e,d.pluginId?o.path:q),l.url=m.checkToAddJsExt(o.url),m.fetchResDef(l);f==k&&(t=new i,B=n.plugins[k]||n,j(l,function(a){var c,d,f;f=a.dynamic;h="normalize"in a?a.normalize(h,b,B)||"":b(h);d=k+"!"+h;c=s[d];if(!(d in s)){c=m.createPluginDef(B,d,e,
h);f||(s[d]=c);var g=function(a){c.resolve(a);f||(s[d]=a)};g.resolve=g;g.reject=c.reject;a.load(h,c.require,g,B)}t!=c&&j(c,t.resolve,t.reject,t.progress)},t.reject));return t||l},getCurrentDefName:function(){var a;if(!c(b.opera,"Opera"))for(var d in A)if(A[d].readyState=="interactive"){a=d;break}return a}};G={require:m.getCjsRequire,exports:m.getCjsExports,module:m.getCjsModule};if(!c(n,"Function")){n=m.extractCfg(n||{});m.checkPreloads(n);var I;(n.apiContext||b)[n.apiName||"curl"]=l;s.curl=l;I=b.define=
function(){var a=m.fixArgs(arguments);o(a)};l.version="0.6.2a";I.amd={plugins:!0,jQuery:!0,curl:"0.6.2a"};s["curl/_privileged"]={core:m,cache:s,cfg:n,_define:o,_curl:l,Promise:i}}})(this);
(function(b,a){function c(){if(!a.body)return!1;w||(w=a.createTextNode(""));try{return a.body.removeChild(a.body.appendChild(w)),w=u,!0}catch(c){return!1}}function d(){var b;b=f[a[g]]&&c();if(!j&&b){j=!0;for(clearTimeout(r);o=n.pop();)o();i&&(a[g]="complete");for(var d;d=e.shift();)d()}return b}function h(){d();j||(r=setTimeout(h,k))}var g="readyState",f={loaded:1,interactive:1,complete:1},e=[],i=a&&typeof a[g]!="string",j=!1,k=10,l,o,n=[],r,u,w;l="addEventListener"in b?function(a,c){a.addEventListener(c,
d,!1);return function(){a.removeEventListener(c,d,!1)}}:function(a,c){a.attachEvent("on"+c,d);return function(){a.detachEvent(c,d)}};a&&!d()&&(n=[l(b,"load"),l(a,"readystatechange"),l(b,"DOMContentLoaded")],r=setTimeout(h,k));define("curl/domReady",function(){function a(c){j?c():e.push(c)}a.then=a;a.amd=!0;return a})})(this,this.document);define("domReady",["curl/domReady"],function(b){return{load:function(a,c,d){b(d)}}});
define("async",function(){return{load:function(b,a,c){function d(a){typeof c.resolve=="function"?c.resolve(a):c(a)}function h(a){typeof c.reject=="function"&&c.reject(a)}a([b],function(a){typeof a.then=="function"?a.then(function(c){arguments.length==0&&(c=a);d(c)},h):d(a)})},analyze:function(b,a,c){c(b)}}});
(function(b,a,c){define("js",["curl/_privileged"],function(b){function h(a,e,f){function g(){h||(i<new Date?f():setTimeout(g,10))}var i,h,j;i=(new Date).valueOf()+(a.timeoutMsec||3E5);f&&a.exports&&setTimeout(g,10);j=b.core.loadScript(a,function(){h=!0;if(a.exports)a.resolved=c(a.exports);!a.exports||a.resolved?e(j):f()},function(a){h=!0;f(a)})}function g(a,c){h(a,function(){var b=e.shift();j=e.length>0;b&&g.apply(null,b);c.resolve(a.resolved||!0)},function(a){c.reject(a)})}var f={},e=[],i=a&&a.createElement("script").async==
!0,j;return{dynamic:!0,load:function(a,c,b,d){var r,u,w,y;r=a.indexOf("!order")>0;u=a.indexOf("!exports=");w=u>0&&a.substr(u+9);y="prefetch"in d?d.prefetch:!0;a=r||u>0?a.substr(0,a.indexOf("!")):a;if(a in f)b(f[a]);else if(f[a]=void 0,c={name:a,url:c.toUrl(a.lastIndexOf(".")<=a.lastIndexOf("/")?a+".js":a),order:r,exports:w,timeoutMsec:d.timeout},d={resolve:function(c){f[a]=c;(b.resolve||b)(c)},reject:b.reject||function(a){throw a;}},r&&!i&&j){if(e.push([c,d]),y)c.mimetype="text/cache",h(c,function(a){a&&
a.parentNode.removeChild(a)},function(){}),c.mimetype=""}else j=j||r,g(c,d)}}})})(this,this.document,function(b){try{return eval(b)}catch(a){}});
(function(b){function a(a,c){var b=a.link;b[l]=b[o]=function(){if(!b.readyState||b.readyState=="complete")y["event-link-onload"]=!0,e(a),c()}}function c(a){for(var a=a.split("!"),c,b=1;c=a[b++];)c=c.split("=",2),a[c[0]]=c.length==2?c[1]:!0;return a}function d(a,c){if(document.createStyleSheet&&(z||(z=document.createStyleSheet()),document.styleSheets.length>=30)){var b,d,e,f=0;e=z;z=null;for(d=document.getElementsByTagName("link");b=d[f];)b.getAttribute("_curl_movable")?(e.addImport(b.href),b.parentNode&&
b.parentNode.removeChild(b)):f++}b=a[n]("link");b.rel="stylesheet";b.type="text/css";b.setAttribute("_curl_movable",!0);if(c)b.href=c;return b}function h(a){var c,b,d=!1;try{if(c=a.sheet||a.styleSheet,(d=(b=c.cssRules||c.rules)?b.length>0:b!==u)&&{}.toString.call(window.chrome)=="[object Chrome]"){c.insertRule("#_cssx_load_test{margin-top:-5px;}",0);if(!q)q=v[n]("div"),q.id="_cssx_load_test",x.appendChild(q);d=v.defaultView.getComputedStyle(q,null).marginTop=="-5px";c.deleteRule(0)}}catch(e){d=e.code==
1E3||e.message.match(/security|denied/i)}return d}function g(a,c){h(a.link)?(e(a),c()):r||setTimeout(function(){g(a,c)},a.wait)}function f(c,b){function d(){e||(e=!0,b())}var e;a(c,d);y["event-link-onload"]||g(c,d)}function e(a){a=a.link;a[l]=a[o]=null}function i(a,c){return a.replace(A,function(a,b){var d=b;E.test(d)||(d=c+d);return'url("'+d+'")'})}function j(a){clearTimeout(j.debouncer);j.accum?j.accum.push(a):(j.accum=[a],s=v.createStyleSheet?v.createStyleSheet():x.appendChild(v.createElement("style")));
j.debouncer=setTimeout(function(){var a,c;a=s;s=u;c=j.accum.join("\n");j.accum=u;c=c.replace(/.+charset[^;]+;/g,"");"cssText"in a?a.cssText=c:a.appendChild(v.createTextNode(c))},0);return s}function k(a){return{cssRules:function(){return a.cssRules||a.rules},insertRule:a.insertRule||function(c,b){var d=c.split(/\{|\}/g);a.addRule(d[0],d[1],b);return b},deleteRule:a.deleteRule||function(c){a.removeRule(c);return c},sheet:function(){return a}}}var l="onreadystatechange",o="onload",n="createElement",
r=!1,u,w={},y={},E=/^\/|^[^:]*:\/\//,A=/url\s*\(['"]?([^'"\)]*)['"]?\)/g,v=b.document,x;if(v)x=v.head||(v.head=v.getElementsByTagName("head")[0]);var z,q,s;define("css",{normalize:function(a,c){var b,d;if(!a)return a;b=a.split(",");d=[];for(var e=0,f=b.length;e<f;e++)d.push(c(b[e]));return d.join(",")},load:function(a,b,e,g){function h(){--o==0&&setTimeout(function(){e(k(q.sheet||q.styleSheet))},0)}var n=(a||"").split(","),o=n.length;if(a)for(var l=n.length-1,m;l>=0;l--,m=!0){var a=n[l],a=c(a),r=
a.shift(),r=b.toUrl(r.lastIndexOf(".")<=r.lastIndexOf("/")?r+".css":r),q=d(v),s={link:q,url:r,wait:g.cssWatchPeriod||50};("nowait"in a?a.nowait!="false":g.cssDeferLoad)?e(k(q.sheet||q.styleSheet)):f(s,h);q.href=r;m?x.insertBefore(q,w[m].previousSibling):x.appendChild(q);w[r]=q}else e({translateUrls:function(a,c){var d;d=b.toUrl(c);d=d.substr(0,d.lastIndexOf("/")+1);return i(a,d)},injectStyle:function(a){return j(a)},proxySheet:function(a){if(a.sheet)a=a.sheet;return k(a)}})},"plugin-builder":"./builder/css"})})(this);
define("jq",["js"],function(){return{load:function(b,a,c){function d(a){typeof c.resolve=="function"?c.resolve(a):c(a)}typeof jQuery!="undefined"?d(jQuery):a(["js!"+b],function(){typeof jQuery!="undefined"?d(jQuery):typeof c.reject=="function"&&c.reject("jQuery NOT defined!")})}}});
define("text",function(){function b(){if(typeof XMLHttpRequest!=="undefined")b=function(){return new XMLHttpRequest};else for(var a=b=function(){throw Error("getXhr(): XMLHttpRequest not available");};d.length>0&&b===a;)(function(a){try{new ActiveXObject(a),b=function(){return new ActiveXObject(a)}}catch(c){}})(d.shift());return b()}function a(a,c,d){var e=b();e.open("GET",a,!0);e.onreadystatechange=function(){e.readyState===4&&(e.status<400?c(e.responseText):d(Error("fetchText() failed. status: "+
e.statusText)))};e.send(null)}function c(a){throw a;}var d=["Msxml2.XMLHTTP","Microsoft.XMLHTTP","Msxml2.XMLHTTP.4.0"];return{load:function(b,d,f){var e=f.resolve||f,f=f.reject||c;a(d.toUrl(b),e,f)},"plugin-builder":"./builder/text"}});
define("i18n",["curl"],function(b){return{load:function(a,c,d){function h(a){typeof d.reject=="function"&&d.reject(a)}function g(c,b){i.length>1&&typeof b=="object"&&f(b,c);typeof c!="undefined"?typeof d.resolve=="function"?d.resolve(c):d(c):h("i18n failed on "+a)}function f(a,c){if(typeof a===typeof c==="object")for(var b in a){var d=a[b];if(typeof d==="object"){var e=c[b];typeof e==="undefined"&&(e={});f(d,e)}}}function e(){i.length>1?(i.pop(),b(i).then(g,e)):h("i18n cannot find "+a)}var i=[a];
$sf.culture!="en"&&(c=a.lastIndexOf("/"),i.push(a.substr(0,c)+"/"+$sf.culture+"/"+a.substr(c+1)));b(i).then(g,e)}}});
$sf.util.Base64={_keyStr:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",encode:function(b){for(var a="",c,d,h,g,f,e,i=0,b=$sf.util.Base64._utf8_encode(b);i<b.length;)c=b.charCodeAt(i++),d=b.charCodeAt(i++),h=b.charCodeAt(i++),g=c>>2,c=(c&3)<<4|d>>4,f=(d&15)<<2|h>>6,e=h&63,isNaN(d)?f=e=64:isNaN(h)&&(e=64),a=a+this._keyStr.charAt(g)+this._keyStr.charAt(c)+this._keyStr.charAt(f)+this._keyStr.charAt(e);return a},decode:function(b){for(var a="",c,d,h,g,f,e=0,b=b.replace(/[^A-Za-z0-9\+\/\=]/g,
"");e<b.length;)c=this._keyStr.indexOf(b.charAt(e++)),d=this._keyStr.indexOf(b.charAt(e++)),g=this._keyStr.indexOf(b.charAt(e++)),f=this._keyStr.indexOf(b.charAt(e++)),c=c<<2|d>>4,d=(d&15)<<4|g>>2,h=(g&3)<<6|f,a+=String.fromCharCode(c),g!=64&&(a+=String.fromCharCode(d)),f!=64&&(a+=String.fromCharCode(h));return a=$sf.util.Base64._utf8_decode(a)},_utf8_encode:function(b){for(var b=b.replace(/\r\n/g,"\n"),a="",c=0;c<b.length;c++){var d=b.charCodeAt(c);d<128?a+=String.fromCharCode(d):(d>127&&d<2048?
a+=String.fromCharCode(d>>6|192):(a+=String.fromCharCode(d>>12|224),a+=String.fromCharCode(d>>6&63|128)),a+=String.fromCharCode(d&63|128))}return a},_utf8_decode:function(b){for(var a="",c=0,d=c1=c2=0;c<b.length;)d=b.charCodeAt(c),d<128?(a+=String.fromCharCode(d),c++):d>191&&d<224?(c2=b.charCodeAt(c+1),a+=String.fromCharCode((d&31)<<6|c2&63),c+=2):(c2=b.charCodeAt(c+1),c3=b.charCodeAt(c+2),a+=String.fromCharCode((d&15)<<12|(c2&63)<<6|c3&63),c+=3);return a}};
define("sf.curl.extend",["curl/_privileged","js"],function(b){var a=document.getElementById("duel");$sf.version="?";var c=$sf.appid="";if(a&&(a=/\/(v[0-9.]*)\/.*appid\=([^\#]*)\#(.*)/.exec(a.src))&&a.length==4)$sf.version=a[1],$sf.appid=a[2],c=a[3];var d=b.core.resolvePathInfo,h=typeof $sf.require.local==="string";b.core.resolvePathInfo=function(a,c){var b,i=/^(starfield|duel)\/([^\s]*.?)/i.exec(a);
if(i&&i.length>=3){i=i[2];$sf.loader>=2&&!h&&(b=$sf.bundle[i],typeof b!=="undefined"&&(i=b));b=i.split("/");var j="/",k=i.lastIndexOf("."),l=k>0?i.substr(k):"";l!=".js"&&l!=".css"&&l!=".pkg"&&(l="",k=-1);k=k>0?i.substr(0,k):i;b.length==1&&(j="/"+k+"/",l==".css"&&(i=$sf.theme+".css"));b={config:c,url:(h?$sf.require.local:l==".css"?$sf.require.css_root:$sf.require.js_root)+j+i};if(i=="jquery.mod")b.url=$sf.require.jquery}else b=d.apply(this,arguments);return b}});
define("starfield/sf.module",[],function(){$sf.util.module=function(b,a){return function(c){function d(b,d,f){for(var g in a)if(a.hasOwnProperty(g)){var h=a[g];c.isPlainObject(h)?this[g]=c.extend(!0,{},h):c.isArray(h)&&(this[g]=c.merge([],h))}this.options=c.extend(!0,{},this.options,d);this.id=f;this.element=b;this._create();this._init()}var h="sf"+b,g="sf-"+b.toLowerCase();$sf||($sf={});if(!$sf.modules)$sf.modules={};if(!$sf.modules.base)$sf.modules.base=function(a,c){this.baseClass=c;this.pluginName=
a;return this},c.extend(!0,$sf.modules.base.prototype,{options:{},_create:function(){},_init:function(){},destroy:function(a){var b=this.id;delete f.instances[b];f.ids=c.grep(f.ids,function(a){return a.id!=b});c.isFunction(a)&&a()},_siblings:function(){var a=this.id;return c.map(f.ids,function(c){return c===a?null:f.instances[c].module})},_log:function(a){window.console&&console.log&&console.log(this.id+": "+a)},_dir:function(a,c){typeof c==="string"&&c.length>0&&this._log(c);window.console&&console.dir&&
console.dir(a)},_initElementId:function(a,c){var b=a.attr("id");if(b==null||b.length==0)b=this._generateId(c),a.attr("id",b)},_generateId:function(a){a=a?a:this.baseClass.toLowerCase();return a+"-"+Math.round(Math.random()*65535)}}),$sf.modules.base.prototype._super=$sf.modules.base.prototype,$sf.modules.base.prototype._execSuper=function(a){var c=[];if(arguments.length>1)for(var b=1;b<arguments.length;b++)c.push(arguments[b]);this._super[a].apply(this,c)};$sf.modules[h]=d;d.prototype=new $sf.modules.base(h,
g);d.prototype.constructor=d;d.constructor=$sf.modules.base;c.extend(!0,d.prototype,a);var f=c.fn[h]=function(a,b){var g="create";a.constructor===String&&(g=a,a=b);var k={initInstance:function(a){var a=c(a),b=a.attr("id");if(b==null||b.length==0)b=h.toLowerCase()+Math.round(Math.random()*65535),a.attr("id",b);var d=f.instances[b]={};f.ids.push(b);d.me=a;return d.meId=b},initPlugin:function(a,b,e,g){var h=function(){b=k.initInstance(e);f.instances[b].module=new d(c(e),g,b)};a?a.module.destroy(h):h()},
getOrDo:function(b,d,f){if(d&&d.module)if(d=d.module,b==="option"||b==="options")return b=d.options[a],c.isPlainObject(b)&&(b=c.extend(!0,{},b)),l=b,!1;else if(b.slice(0,1)!=="_"&&c.isFunction(d[b]))return f=!1,c.isArray(a)||(a=[a]),f=d[b].apply(d,a),typeof f!=="undefined"&&(l=f),!1;else k.log("invalid command/property: "+b);else k.log("couldn't find instance for ["+f+"] to execute "+b)},log:function(a){window.console&&console.log&&console.log(a)}};if(!f.instances)f.instances={};if(!f.ids)f.ids=[];
var l=this;this.each(function(){var b=c(this).attr("id"),d=f.instances[b];if(g==="create")k.initPlugin(d,b,this,a);else if(g==="destroy")d&&d.module&&d.module.destroy();else if(d&&d.module&&d.module._init(),!k.getOrDo(g,d,b))return!1});return l};return f}($sf.getjQuery())}});if(typeof String.prototype.sfFormat!="object")String.prototype.sfFormat=function(){var b=arguments;return this.replace(/{(\d+)}/g,function(a,c){return typeof b[c]!="undefined"?b[c]:a})};
define("starfield/sf.util",[],function(){function b(){function a(c){if(c.css("position")=="static")return 0;c=Number(c.css("zIndex"));isNaN(c)&&(c=0);return c}function b(g,f,e){f=isNaN(f)?0:f;if(g.length===0)return f;var h=g.get(0).tagName.toLowerCase()!="body";if(g&&g.length>0&&h){var j=a(g);j>f&&(f=j);if(f===0||e&&h)return b(g.parent(),f,e)}return f}function h(b){b=b.parent();if(b.length===0)return null;var d=b.get(0).tagName.toLowerCase()!=="body",e=b.css("position").toLowerCase()!=="fixed";return b&&
b.length>0&&d&&e&&a(b)===0?h(b.parent()):b}return{get:function(a){return b(a,0,!1)},getTop:function(a){return b(a,0,!0)},getAssigned:a,getParent:h,getStackingParent:function(a){var c=null;a.parentsUntil("body").each(function(){if($(this).css("position").toLowerCase()==="fixed")return c=$(this),!1});return c},max:function(){var b=0;($sf.util.ua.ie?$("body *"):$("*:visible")).each(function(d,e){var h=$(e),h=a(h);h>b&&(b=h)});return b}}}function a(a,b){var h=typeof a==="string"&&a.length>0?a+": ":"",
g=typeof window.console!=="undefined",b=typeof b==="string"&&b.length===0?void 0:b,f=typeof b==="string"&&window.location.href.indexOf(b+"=true")>-1||typeof b!=="string";return{log:function(a){g&&f&&console.log&&console.log(h+a)},dir:function(a){g&&f&&console.dir&&console.dir(a)}}}$sf.util.util=function(c){c=$.extend({},c);return{zIndex:b(),logger:a(c.logId)}};$sf.util.zIndex=b();$sf.util.logger=a;$sf.util.context=function(a,b){function h(){f||$("iframe",b.document).each(function(){this.contentWindow===
a&&(f=$(this))});return f}function g(e,f){var g=e.offset();if(b!==a){var k=h().offset(),l=typeof f==="boolean"?f:e.css("position")==="fixed";g.top=Math.ceil(g.top+k.top-(l?$(b).scrollTop():$(a).scrollTop()));g.left=Math.ceil(g.left+k.left-(l?$(b).scrollLeft():$(a).scrollLeft()))}return g}var f=null;return{isSingle:function(){return b===a},ext:{iframe:h,offset:g,window:function(){return b},document:function(){return b.document},body:function(){return b.document.body}},intr:{isInBounds:function(e,f){var j=
g(e,f),k=b!==a,l=!k?b:h(),o=!k?{top:0,left:0}:l.offset();j.top+=!k?0:$(a).scrollTop();j.left+=!k?0:$(a).scrollLeft();j.right=Math.ceil(j.left+e.outerWidth());j.bottom=Math.ceil(j.top+e.outerHeight());o.left+=$(a).scrollLeft();o.top+=$(a).scrollTop();o.right=Math.ceil(o.left+$(l).width());o.bottom=Math.ceil(o.top+$(l).height());return j.left>=o.left&&j.right<=o.right&&j.top>=o.top&&j.bottom<=o.bottom},window:function(){return a},document:function(){return a.document},body:function(){return a.document.body}}}};
return $sf.util.util});
define("starfield/sf.ua",[],function(){var b=$sf.uas={win:/Windows NT ([0-9\.a-z]*)/i,osx:/Mac OS X ([0-9\.a-z\_]*)/i,ie:/MSIE\s([0-9\.a-z]*)/i,trident:/Trident\/([0-9\.a-z]*)/i,ff:/Firefox\/([0-9\.a-z]*)/i,webkit:/AppleWebKit\/([0-9\.a-z]*)/i,mobile:/iPhone|Android|PlayBook|BlackBerry|Windows Phone/i},a=$sf.UA=function(a,b){if(typeof b!=="string")b=navigator.userAgent;this.exp=a;var c=a.exec(b);this.major=this.minor=0;if((this.found=c?!0:!1)&&c.length>=2){var c=this.version=c[1],d=c.split(".");d.length==
0&&(d=c.split("_"));this.major=d.length>=1?parseInt(d[0]):0;if(this.major===NaN)this.major=0;this.minor=d.length>=2?parseInt(d[1]):0;if(this.minor===NaN)this.minor=0}},c=a.prototype;c.compare=function(a,b){typeof a!=="number"&&(a=0);typeof b!=="number"&&(b=0);return this.major>a?1:this.major<a?-1:this.minor>b?1:this.minor<b?-1:0};c.toString=function(){return this.version};var d=$sf.util.ua={version:"?"},c=function(b,c){var f=new a(b);if(d[c]=f.found)d.version=f.version,d.major=f.major,d.minor=f.minor};
c(b.win,"win");c(b.osx,"osx");c(b.ff,"firefox");c(b.webkit,"webkit");c(b.trident,"trident");if(d.trident&&d.major<=7)d.ieCompat=!0;c(b.ie,"ie");d.ie6=d.ie&&d.major<=6;d.ie7=d.ie&&d.major==7;d.hasFixed=d.ie6!==!0;return d});
define("starfield/sf.selector",["jq!starfield/jquery.mod"],function(){$sf.util.selector=function(b,a){(function(c){var d={};d[b]=function(b,d,f){if(a.root){b=c(b);f=f[3];d=b.is(a.root.selector);if(!f||f=="")return d;var f=f.split(","),e=!1,i="root",j;for(j in a){if(a.hasOwnProperty(j)&&j!=="root"){var k=c.grep(f,function(a){return a!=j});k.length<f.length&&(f=k,e=b.is(a[j].selector),i=j)}if(e)break}i==="root"&&d&&(e=!0);if(e&&(a[i].states||a[i].tests)){e=f.length==0;for(d=0;d<f.length;d++){var l=
f[d],k=l.split("=");k.length>1?(l=a[i].tests&&a[i].tests[k[0]]?a[i].tests[k[0]]:null,c.isFunction(l)&&(e=l(b,k[1]))):(l=a[i].states&&a[i].states[l]?a[i].states[l]:null,c.isFunction(l)&&(e=l(b)));if(!e)break}}return e}};c.extend(c.expr[":"],d)})($sf.getjQuery())};return $sf.util.selector});
$sf.util.storage=function(b){if(!(this instanceof $sf.util.storage))return new $sf.util.storage(b);this.cookiesDisabled=!1;this.cookieTimeout=365;this.localStorageDisabled=!1;if(typeof b=="object"){if(typeof b.cookiesDisabled!="undefined")this.cookiesDisabled=b.cookiesDisabled;if(typeof b.localStorageDisabled!="undefined")this.localStorageDisabled=b.localStorageDisabled;if(typeof b.cookieTimeout!="undefined")this.cookieTimeout=b.cookieTimeout}};
$sf.util.storage.prototype.getItem=function(b,a){var c=a,b="sf-"+b;if(window.localStorage&&this.localStorageDisabled===!1)c=window.localStorage[b];else if(this.cookiesDisabled===!1){var d,h,g,f=document.cookie.split(";");for(d=0;d<f.length;d++)if(h=f[d].substr(0,f[d].indexOf("=")),g=f[d].substr(f[d].indexOf("=")+1),h=h.replace(/^\s+|\s+$/g,""),h==b){c=unescape(g);break}}return typeof c=="undefined"||c===null?a:c};
$sf.util.storage.prototype.setItem=function(b,a){b="sf-"+b;if(window.localStorage&&this.localStorageDisabled===!1)window.localStorage.setItem(b,a);else if(this.cookiesDisabled===!1){var c=new Date;c.setDate(c.getDate()+this.cookieTimeout);a=escape(a)+(this.cookieTimeout==null?"":"; expires="+c.toUTCString());document.cookie=b+"="+a}};
$sf.util.storage.prototype.getLength=function(){if(window.localStorage&&this.localStorageDisabled===!1)return window.localStorage.length;else if(this.cookiesDisabled===!1)return document.cookie.split(";").length;return 0};$sf.util.storage.prototype.removeItem=function(b){b="sf-"+b;if(window.localStorage&&this.localStorageDisabled===!1)window.localStorage.removeItem(b);else if(this.cookiesDisabled===!1){var a=new Date;a.setDate(a.getDate()-1);a="; expires="+a.toUTCString();document.cookie=b+"="+a}};
$sf.util.storage.prototype.isEnabled=function(){var b=!1;try{if(b=window.localStorage&&this.localStorageDisabled,!b&&this.cookiesDisabled===!1){var a=navigator.cookieEnabled?!0:!1;if(typeof navigator.cookieEnabled=="undefined"&&!a)document.cookie="testcookie",a=document.cookie.indexOf("testcookie")!=-1?!0:!1;b=a}}catch(c){}return b};
define("starfield/sf.event",[],function(){function b(a){a=Object.prototype.toString.call(a);return a.substr(8,a.length-9)}var a={};return $sf.util.event={on:function(){var c=[].slice.call(arguments),d=c.length,h=!1,g=!1;if(d>1&&d<4){var f=c[d-1];d===3&&(g=c[1]);if(b(f)==="Function"&&(b(c[0])==="String"&&(c[0]=c[0].split(" ")),b(c[0])==="Array"))for(d=0;d<c[0].length;d++){var e=c[0][d],i=g;if(e){!i&&e.split(".",2).length>=2&&(i=e.split(".",2),e=i.shift(),i=i.shift());if(!i){i=0;if(a[e])for(;a[e]["_ns_"+
i];)i++;i="_ns_"+i}a[e]||(a[e]={});a[e][i]||(a[e][i]=[]);h||(h=[]);h.push(e+"."+i);a[e][i].push(f)}}}return h},off:function(c){var d=b(c);d==="String"?c=c.split(" "):d==="Function"&&(c=[c]);if(b(c)==="Array")for(var h=0;h<c.length;h++){var g=c[h];if((d=b(g))==="String")g.split(".",2).length>=2?(d=g.split(".",2),g=d.shift(),a[g]&&delete a[g][d.shift()]):a[g]&&delete a[g];else if(d==="Function")for(var f in a)for(var e in a[f])for(var i in a[f][e])g===a[f][e][i]&&delete a[f][e][i]}},trigger:function(c){b(c)===
"String"&&(c=c.split(" "));if(b(c)==="Array")for(var d=[].slice.call(arguments,1),h=0;h<c.length;h++){var g=c[h],f;if(g.split(".",2).length>=2){if(f=g.split(".",2),g=f.shift(),f=f.shift(),a[g]&&a[g][f])for(var e in a[g][f])a[g][f][e]({event:g+"."+f,args:d})}else if(a[g])for(var i in a[g])for(e in a[g][i])a[g][i][e]({event:g+"."+i,args:d})}}}});$sf.preload>=1&&require("css!starfield/sf.core.css");$sf.preload>=2&&require("starfield/sf.core.pkg");
$sf.plabel!=1&&require("domReady!",function(){document.body.className+=(document.body.className==""?"":" ")+"sf-pl"});

/*
     FILE ARCHIVED ON 21:58:33 Nov 19, 2014 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 13:27:08 Jan 07, 2019.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  LoadShardBlock: 370.526 (3)
  esindex: 0.009
  captures_list: 396.986
  CDXLines.iter: 11.771 (3)
  PetaboxLoader3.datanode: 352.078 (5)
  exclusion.robots: 0.22
  exclusion.robots.policy: 0.205
  RedisCDXSource: 5.799
  PetaboxLoader3.resolve: 113.137 (4)
  load_resource: 177.954
*/